import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import type { ProcessSpan,SessionTimeline as Timeline } from '../src/timeline/model';

import { processSummary, semanticToolLabel, SessionTimeline } from '../src/timeline/SessionTimeline';

const process=(events=1,state:ProcessSpan['state']='completed'):ProcessSpan=>({id:'worker:a',actor:'worker',label:'Implementation worker',state,startedAt:'2026-01-01T00:00:00Z',finishedAt:state==='live'?undefined:'2026-01-01T00:05:00Z',stream:Array.from({length:events},(_,index)=>({id:`e${index}`,kind:'command',lifecycle:'completed',title:`Command ${index}`,occurredAt:'2026-01-01T00:00:00Z',authority:'activity'})),streamBounds:{complete:true,hasEarlier:false}});
const timeline=(revision='r1',events=1,state:ProcessSpan['state']='completed'):Timeline=>({revision,session:{id:'s1',intent:'Build the timeline',mode:'AUTO',state:state==='live'?'live':'settled',startedAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:05:00Z'},spans:[process(events,state)]});

describe('session timeline behavior',()=>{let host:HTMLDivElement,root:Root;beforeEach(()=>{host=document.createElement('div');document.body.append(host);root=createRoot(host)});afterEach(()=>{act(()=>root.unmount());host.remove()});
  it('gives the scroll owner an explicit remaining-space host and exposes bootstrap diagnostics',async()=>{const diagnostics:unknown[]=[];Object.defineProperty(HTMLElement.prototype,'getBoundingClientRect',{configurable:true,value:()=>({width:900,height:640,top:0,right:900,bottom:640,left:0,x:0,y:0,toJSON(){return{}}})});await act(async()=>root.render(<SessionTimeline timeline={timeline()} onLoadEarlier={async()=>{}} onBootstrapDiagnostic={(value)=>diagnostics.push(value)}/>));expect(host.querySelector('.timeline-panel > .timeline-list-host > .timeline-list')).not.toBeNull();expect(diagnostics).toContainEqual(expect.objectContaining({suppliedClusters:1,viewportWidth:900,viewportHeight:640,listLoaded:true,renderedItems:1}))});
  it('starts at live edge, follows only within 40px, and Return to live rearms at the real edge',async()=>{await act(async()=>root.render(<SessionTimeline timeline={timeline('r1',1,'live')} onLoadEarlier={async()=>{}}/>));const list=host.querySelector('.timeline-list') as HTMLDivElement;Object.defineProperties(list,{scrollHeight:{configurable:true,value:1000},clientHeight:{configurable:true,value:200},scrollTop:{configurable:true,writable:true,value:780}});await act(async()=>list.dispatchEvent(new Event('scroll',{bubbles:true})));list.scrollTop=500;await act(async()=>list.dispatchEvent(new Event('scroll',{bubbles:true})));await act(async()=>root.render(<SessionTimeline timeline={timeline('r2',2,'live')} onLoadEarlier={async()=>{}}/>));expect(host.textContent).toContain('Return to live · 1 updates');await act(async()=>{(host.querySelector('.return-live') as HTMLButtonElement).click()});expect(list.scrollTop).toBe(1000);expect(host.textContent).not.toContain('Return to live')});
  it('expands settled content as normal row flow and preserves an independently scrollable stream',async()=>{await act(async()=>root.render(<SessionTimeline timeline={timeline()} onLoadEarlier={async()=>{}}/>));await act(async()=>{(host.querySelector('.span-head') as HTMLButtonElement).click()});const disclosure=host.querySelector('[data-testid="disclosure:worker:a"]');expect(disclosure).not.toBeNull();expect(disclosure?.parentElement?.classList.contains('cluster-row')).toBe(true);expect(disclosure?.querySelector('[data-testid="stream:worker:a"]')).not.toBeNull()});
  it('renders the bounded process page in natural variable-height flow',async()=>{await act(async()=>root.render(<SessionTimeline timeline={timeline('bounded',120,'live')} onLoadEarlier={async()=>{}}/>));expect(host.querySelectorAll('.stream-item')).toHaveLength(120);expect(host.querySelector('.stream-virtual-space')).toBeNull();const first=host.querySelector('.tool-row') as HTMLDetailsElement;await act(async()=>{(first.querySelector('summary') as HTMLElement).click()});expect(first.open).toBe(true)});
  it('lets multiline narration and raw detail take natural height without overlap math',async()=>{const value=timeline();value.spans[0]!.stream=[{id:'n',kind:'narration',lifecycle:'completed',title:'First line\nSecond line\nThird line',occurredAt:'x',authority:'activity'},{id:'r',kind:'read',lifecycle:'completed',title:'Read D:\\repo\\router.js',detail:'line one\nline two\nline three',occurredAt:'x',authority:'activity'}];await act(async()=>root.render(<SessionTimeline timeline={value} onLoadEarlier={async()=>{}}/>));await act(async()=>{(host.querySelector('.span-head') as HTMLElement).click()});const rows=host.querySelectorAll('.inline-disclosure .stream-item');expect(rows).toHaveLength(2);expect((rows[0] as HTMLElement).style.height).toBe('');expect((rows[1] as HTMLElement).style.transform).toBe('');await act(async()=>{(rows[1]!.querySelector('summary') as HTMLElement).click()});expect(rows[1]!.querySelector('pre')?.textContent).toContain('line three')});
  it('keeps long real narration explicitly accessible outside the tool rows',async()=>{const long='The first investigation rules out the migration hypothesis. '.repeat(20);const value=timeline();value.spans[0]!.stream=[{id:'reason',kind:'narration',lifecycle:'completed',title:long,occurredAt:'2026-01-01T00:01:00Z',authority:'activity'}];await act(async()=>root.render(<SessionTimeline timeline={value} onLoadEarlier={async()=>{}}/>));await act(async()=>{(host.querySelector('.span-head') as HTMLButtonElement).click()});const toggle=host.querySelector('.narration-disclosure summary') as HTMLElement;expect(toggle.textContent).toContain('Read full');await act(async()=>toggle.click());expect(host.querySelector('[data-testid="narration-full:reason"]')?.textContent).toBe(long)});
  it('keeps action semantics in normal tool labels',()=>{expect(semanticToolLabel({id:'r',kind:'read',lifecycle:'completed',title:'Read D:\\repo\\src\\router.js',occurredAt:'x',authority:'activity'})).toBe('Read router.js');expect(semanticToolLabel({id:'s',kind:'search',lifecycle:'completed',title:'Search selectRoute',occurredAt:'x',authority:'activity'})).toBe('Search selectRoute');expect(semanticToolLabel({id:'e',kind:'edit',lifecycle:'completed',title:'Edit D:\\repo\\router.js',occurredAt:'x',authority:'activity'})).toBe('Edit router.js');expect(semanticToolLabel({id:'t',kind:'todo',lifecycle:'completed',title:'Todowrite',occurredAt:'x',authority:'activity'})).toBe('Update tasks')});
  it('shows ordinary live appends immediately and paces only a large backlog',async()=>{vi.useFakeTimers();const value=timeline('p1',1,'live');value.spans[0]!.stream=[{id:'reason',kind:'narration',lifecycle:'updated',title:'Checking routes.',occurredAt:'x',authority:'activity'}];await act(async()=>root.render(<SessionTimeline timeline={value} onLoadEarlier={async()=>{}}/>));value.revision='p2';value.spans[0]!.stream[0]={...value.spans[0]!.stream[0]!,title:'Checking routes. Small append.'};await act(async()=>root.render(<SessionTimeline timeline={{...value,spans:[{...value.spans[0]!,stream:[value.spans[0]!.stream[0]!]}]}} onLoadEarlier={async()=>{}}/>));expect(host.querySelector('[data-testid="narration:reason"]')?.textContent).toBe('Checking routes. Small append.');const large='Checking routes. Small append.'+'.'.repeat(700);value.revision='p3';await act(async()=>root.render(<SessionTimeline timeline={{...value,spans:[{...value.spans[0]!,stream:[{...value.spans[0]!.stream[0]!,title:large}]}]}} onLoadEarlier={async()=>{}}/>));expect(host.querySelector('[data-testid="narration:reason"]')?.textContent).toBe('Checking routes. Small append.');await act(async()=>vi.advanceTimersByTimeAsync(24));const paced=host.querySelector('[data-testid="narration:reason"]')?.textContent??'';expect(paced.length).toBeGreaterThan('Checking routes. Small append.'.length);expect(paced.length).toBeLessThan(large.length);vi.useRealTimers()});
  it('prioritizes consequential failure over preceding narration',()=>{const failed=process();failed.state='failed';failed.stream=[{id:'n',kind:'narration',lifecycle:'completed',title:'Still investigating',occurredAt:'x',authority:'activity'},{id:'f',kind:'command',lifecycle:'failed',title:'node --test failed',occurredAt:'x',authority:'activity'}];expect(processSummary(failed)).toBe('node --test failed')});
});
