import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import type { ProcessSpan,SessionTimeline as Timeline } from '../src/timeline/model';

const legend=vi.hoisted(()=>({props:null as Record<string,unknown>|null,scrollToEnd:vi.fn(async()=>{})}));
vi.mock('@legendapp/list/react',async()=>{const React=await import('react');return{LegendList:React.forwardRef((props:Record<string,unknown>,ref)=>{legend.props=props;React.useImperativeHandle(ref,()=>({scrollToEnd:legend.scrollToEnd}));const data=props.data as unknown[];const render=props.renderItem as (value:{item:unknown;index:number})=>React.ReactNode;React.useEffect(()=>{(props.onLoad as undefined|(()=>void))?.()},[]);return React.createElement('div',{'data-testid':'legend-list',className:props.className},data.map((item,index)=>React.createElement(React.Fragment,{key:(props.keyExtractor as (item:unknown)=>string)(item)},render({item,index}))))})}});
import { SessionTimeline } from '../src/timeline/SessionTimeline';

const process=(events=1,state:ProcessSpan['state']='completed'):ProcessSpan=>({id:'worker:a',actor:'worker',label:'Implementation worker',state,startedAt:'2026-01-01T00:00:00Z',finishedAt:state==='live'?undefined:'2026-01-01T00:05:00Z',stream:Array.from({length:events},(_,index)=>({id:`e${index}`,kind:'command',lifecycle:'completed',title:`Command ${index}`,occurredAt:'2026-01-01T00:00:00Z',authority:'activity'})),streamBounds:{complete:true,hasEarlier:false}});
const timeline=(revision='r1',events=1,state:ProcessSpan['state']='completed'):Timeline=>({revision,session:{id:'s1',intent:'Build the timeline',mode:'AUTO',state:state==='live'?'live':'settled',startedAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:05:00Z'},spans:[process(events,state)]});

describe('session timeline behavior',()=>{let host:HTMLDivElement,root:Root;beforeEach(()=>{host=document.createElement('div');document.body.append(host);root=createRoot(host);legend.props=null;legend.scrollToEnd.mockClear()});afterEach(()=>{act(()=>root.unmount());host.remove()});
  it('gives the list an explicit remaining-space host and exposes bootstrap diagnostics',async()=>{const diagnostics:unknown[]=[];Object.defineProperty(HTMLElement.prototype,'getBoundingClientRect',{configurable:true,value:()=>({width:900,height:640,top:0,right:900,bottom:640,left:0,x:0,y:0,toJSON(){return{}}})});await act(async()=>root.render(<SessionTimeline timeline={timeline()} onLoadEarlier={async()=>{}} onBootstrapDiagnostic={(value)=>diagnostics.push(value)}/>));expect(host.querySelector('.timeline-panel > .timeline-list-host > .timeline-list')).not.toBeNull();expect(legend.props?.style).toBeUndefined();expect(diagnostics).toContainEqual(expect.objectContaining({suppliedClusters:1,viewportWidth:900,viewportHeight:640,listLoaded:true,renderedItems:1}))});
  it('starts at live edge, follows only within 40px, and Return to live rearms at the real edge',async()=>{await act(async()=>root.render(<SessionTimeline timeline={timeline('r1',1,'live')} onLoadEarlier={async()=>{}}/>));expect(legend.props?.initialScrollAtEnd).toBe(true);expect(legend.props?.maintainScrollAtEnd).toBe(true);expect(legend.props?.maintainScrollAtEndThreshold).toBeGreaterThan(0);await act(async()=>{(legend.props?.onScroll as Function)({nativeEvent:{contentOffset:{y:780},contentSize:{height:1000},layoutMeasurement:{height:200}}})});expect(legend.props?.maintainScrollAtEnd).toBe(true);await act(async()=>{(legend.props?.onScroll as Function)({nativeEvent:{contentOffset:{y:500},contentSize:{height:1000},layoutMeasurement:{height:200}}})});expect(legend.props?.maintainScrollAtEnd).toBe(false);await act(async()=>root.render(<SessionTimeline timeline={timeline('r2',2,'live')} onLoadEarlier={async()=>{}}/>));expect(host.textContent).toContain('Return to live · 1 new');expect(legend.scrollToEnd).not.toHaveBeenCalled();await act(async()=>{(host.querySelector('.return-live') as HTMLButtonElement).click()});expect(legend.scrollToEnd).toHaveBeenCalledTimes(1);expect(legend.props?.maintainScrollAtEnd).toBe(false);await act(async()=>{(legend.props?.onScroll as Function)({nativeEvent:{contentOffset:{y:800},contentSize:{height:1000},layoutMeasurement:{height:200}}})});expect(legend.props?.maintainScrollAtEnd).toBe(true)});
  it('expands settled content as normal row flow and preserves an independently scrollable stream',async()=>{await act(async()=>root.render(<SessionTimeline timeline={timeline()} onLoadEarlier={async()=>{}}/>));await act(async()=>{(host.querySelector('.span-head') as HTMLButtonElement).click()});const disclosure=host.querySelector('[data-testid="disclosure:worker:a"]');expect(disclosure).not.toBeNull();expect(disclosure?.parentElement?.classList.contains('cluster-row')).toBe(true);expect(disclosure?.querySelector('[data-testid="stream:worker:a"]')).not.toBeNull()});
  it('virtualizes a bounded 500-event process page and measures rendered work',async()=>{const started=performance.now();await act(async()=>root.render(<SessionTimeline timeline={timeline('large',500,'live')} onLoadEarlier={async()=>{}}/>));expect(host.querySelectorAll('.stream-row').length).toBeLessThan(20);expect((host.querySelector('.stream-virtual-space') as HTMLElement).style.height).toBe('27000px');expect(performance.now()-started).toBeLessThan(1000)});
  it('keeps long real narration explicitly accessible outside the fixed tool row',async()=>{const long='The first investigation rules out the migration hypothesis. '.repeat(20);const value=timeline();value.spans[0]!.stream=[{id:'reason',kind:'narration',lifecycle:'completed',title:long,occurredAt:'2026-01-01T00:01:00Z',authority:'activity'}];await act(async()=>root.render(<SessionTimeline timeline={value} onLoadEarlier={async()=>{}}/>));await act(async()=>{(host.querySelector('.span-head') as HTMLButtonElement).click()});const toggle=host.querySelector('.narration-toggle') as HTMLButtonElement;expect(toggle.textContent).toContain('Read full');await act(async()=>toggle.click());expect(host.querySelector('[data-testid="narration:reason"]')?.textContent).toBe(long)});
});
