import { act } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import type { ProcessSpan,SessionTimeline as Timeline } from '../src/timeline/model';

import { processSummary, semanticToolLabel, SessionTimeline } from '../src/timeline/SessionTimeline';

const process=(events=1,state:ProcessSpan['state']='completed'):ProcessSpan=>({id:'worker:a',actor:'worker',label:'Implementation worker',state,startedAt:'2026-01-01T00:00:00Z',finishedAt:state==='live'?undefined:'2026-01-01T00:05:00Z',stream:Array.from({length:events},(_,index)=>({id:`e${index}`,kind:'command',lifecycle:'completed',title:`Command ${index}`,occurredAt:'2026-01-01T00:00:00Z',authority:'activity'})),streamBounds:{complete:true,hasEarlier:false}});
const timeline=(revision='r1',events=1,state:ProcessSpan['state']='completed'):Timeline=>({revision,session:{id:'s1',intent:'Build the timeline',mode:'AUTO',state:state==='live'?'live':'settled',startedAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:05:00Z'},spans:[process(events,state)]});
const parallelTimeline=():Timeline=>{const first=process();const second={...process(),id:'worker:b',label:'Exploration worker',startedAt:'2026-01-01T00:01:00Z',finishedAt:'2026-01-01T00:04:00Z'};return{...timeline(),spans:[first,second]}};

describe('session timeline behavior',()=>{let host:HTMLDivElement,root:Root;beforeEach(()=>{host=document.createElement('div');document.body.append(host);root=createRoot(host)});afterEach(()=>{act(()=>root.unmount());host.remove()});
  it('gives the scroll owner an explicit remaining-space host and exposes bootstrap diagnostics',async()=>{const diagnostics:unknown[]=[];Object.defineProperty(HTMLElement.prototype,'getBoundingClientRect',{configurable:true,value:()=>({width:900,height:640,top:0,right:900,bottom:640,left:0,x:0,y:0,toJSON(){return{}}})});await act(async()=>root.render(<SessionTimeline timeline={timeline()} onLoadEarlier={async()=>{}} onBootstrapDiagnostic={(value)=>diagnostics.push(value)}/>));expect(host.querySelector('.timeline-panel > .timeline-list-host > .timeline-list')).not.toBeNull();expect(diagnostics).toContainEqual(expect.objectContaining({suppliedClusters:1,viewportWidth:900,viewportHeight:640,listLoaded:true,renderedItems:1}))});
  it('starts at live edge, follows only within 40px, and Return to live rearms at the real edge',async()=>{await act(async()=>root.render(<SessionTimeline timeline={timeline('r1',1,'live')} onLoadEarlier={async()=>{}}/>));const list=host.querySelector('.timeline-list') as HTMLDivElement;Object.defineProperties(list,{scrollHeight:{configurable:true,value:1000},clientHeight:{configurable:true,value:200},scrollTop:{configurable:true,writable:true,value:780}});await act(async()=>list.dispatchEvent(new Event('scroll',{bubbles:true})));list.scrollTop=500;await act(async()=>list.dispatchEvent(new Event('scroll',{bubbles:true})));await act(async()=>root.render(<SessionTimeline timeline={timeline('r2',2,'live')} onLoadEarlier={async()=>{}}/>));expect(host.textContent).toContain('Return to live · 1 updates');await act(async()=>{(host.querySelector('.return-live') as HTMLButtonElement).click()});expect(list.scrollTop).toBe(1000);expect(host.textContent).not.toContain('Return to live')});
  it('expands the same process block in place without a duplicate continuation',async()=>{await act(async()=>root.render(<SessionTimeline timeline={timeline()} onLoadEarlier={async()=>{}}/>));const card=host.querySelector('[data-testid="process:worker:a"]')!;await act(async()=>{(card.querySelector('.process-header') as HTMLButtonElement).click()});expect(card.querySelector('[data-testid="stream:worker:a"]')).not.toBeNull();expect(host.querySelectorAll('[data-testid="process:worker:a"]')).toHaveLength(1);expect(host.querySelector('.inline-disclosure')).toBeNull()});
  it('renders a bounded page in natural flow and compresses routine receipts',async()=>{await act(async()=>root.render(<SessionTimeline timeline={timeline('bounded',120,'live')} onLoadEarlier={async()=>{}}/>));expect(host.querySelector('.stream-virtual-space')).toBeNull();expect(host.querySelectorAll('.tool-group')).toHaveLength(1);expect(host.textContent).toContain('Ran 120 commands')});
  it('lets multiline narration and raw detail take natural height',async()=>{const value=timeline();value.spans[0]!.stream=[{id:'n',kind:'narration',lifecycle:'completed',title:'First line\nSecond line\nThird line',occurredAt:'x',authority:'activity'},{id:'r',kind:'read',lifecycle:'completed',title:'Read D:\\repo\\router.js',detail:'line one\nline two\nline three',occurredAt:'x',authority:'activity'}];await act(async()=>root.render(<SessionTimeline timeline={value} onLoadEarlier={async()=>{}}/>));await act(async()=>{(host.querySelector('.process-header') as HTMLElement).click()});expect(host.querySelector('[data-testid="narration:n"]')?.textContent).toContain('Third line');const tool=host.querySelector('.agent-tool') as HTMLDetailsElement;await act(async()=>{(tool.querySelector('summary') as HTMLElement).click()});expect(tool.querySelector('pre')?.textContent).toContain('line three')});
  it('renders full public narration as primary Markdown prose',async()=>{const long='The first investigation rules out the migration hypothesis. '.repeat(20);const value=timeline();value.spans[0]!.stream=[{id:'reason',kind:'narration',lifecycle:'completed',title:long,occurredAt:'2026-01-01T00:01:00Z',authority:'activity'}];await act(async()=>root.render(<SessionTimeline timeline={value} onLoadEarlier={async()=>{}}/>));await act(async()=>{(host.querySelector('.process-header') as HTMLButtonElement).click()});expect(host.querySelector('[data-testid="narration:reason"]')?.textContent).toBe(long.trim())});
  it('opens the complete request from the title itself',async()=>{const value=timeline();value.session.intent='Investigate the routing failure through two independent workstreams. '.repeat(30);await act(async()=>root.render(<SessionTimeline timeline={value} onLoadEarlier={async()=>{}}/>));await act(async()=>{(host.querySelector('.session-title') as HTMLButtonElement).click()});expect(host.querySelector('[role="dialog"]')?.textContent).toContain(value.session.intent)});
  it('drops duration scaling and uses Ctrl-wheel readability scaling',async()=>{localStorage.removeItem('delegate-wave.feed-scale');await act(async()=>root.render(<SessionTimeline timeline={timeline()} onLoadEarlier={async()=>{}}/>));expect(host.querySelector('.zoom')).toBeNull();const feed=host.querySelector('.coordination-feed') as HTMLElement;await act(async()=>feed.dispatchEvent(new WheelEvent('wheel',{bubbles:true,ctrlKey:true,deltaY:-1})));expect(localStorage.getItem('delegate-wave.feed-scale')).not.toBe('1')});
  it('keeps settled timing as focus metadata without duplicated resting timestamp chrome',async()=>{await act(async()=>root.render(<SessionTimeline timeline={timeline()} onLoadEarlier={async()=>{}}/>));expect(host.querySelectorAll('.feed-time')).toHaveLength(1);const header=host.querySelector('.process-header') as HTMLButtonElement;expect(header.querySelector('time')).toBeNull();expect(header.querySelector('.process-meta')?.textContent).toContain('5m 00s');expect(header.getAttribute('aria-label')).toContain('duration 5m 00s');expect(host.querySelector('.session-state')).toBeNull();expect(host.querySelector('.latest-rule')).toBeNull()});
  it('keeps consequential live, failure, and waiting states visible at rest',async()=>{const value=timeline();value.spans=[process(1,'live'),{...process(),id:'worker:failed',state:'failed'},{...process(),id:'worker:waiting',state:'waiting'}];await act(async()=>root.render(<SessionTimeline timeline={value} onLoadEarlier={async()=>{}}/>));expect([...host.querySelectorAll('.consequential-state')].map((node)=>node.textContent)).toEqual(expect.arrayContaining(['Live','Failed','Needs input']))});
  it('reflows either expanded parallel worker full width without duplication and restores compact lanes',async()=>{await act(async()=>root.render(<SessionTimeline timeline={parallelTimeline()} onLoadEarlier={async()=>{}}/>));const group=host.querySelector('.parallel-group')!;const cards=[...group.querySelectorAll<HTMLElement>('.process-card')];expect(cards).toHaveLength(2);expect(cards.map((card)=>card.style.gridColumn)).toEqual(['1','2']);await act(async()=>{(cards[1]!.querySelector('.process-header') as HTMLButtonElement).click()});expect(cards[1]!.classList.contains('expanded')).toBe(true);expect(cards[1]!.style.gridColumn).toBe('1 / -1');expect(group.querySelectorAll('[data-testid="process:worker:b"]')).toHaveLength(1);expect(group.querySelector('[data-testid="process:worker:a"]')).not.toBeNull();expect(group.textContent).toContain('Parallel work');await act(async()=>{(cards[1]!.querySelector('.process-header') as HTMLButtonElement).click()});expect(cards[1]!.classList.contains('expanded')).toBe(false);expect(cards[1]!.style.gridColumn).toBe('2')});
  it('gives only an expanded live process an independent free-scroll and Return to live control',async()=>{await act(async()=>root.render(<SessionTimeline timeline={timeline('live-scroll',3,'live')} onLoadEarlier={async()=>{}}/>));const card=host.querySelector('.process-card')!;const viewport=card.querySelector('.process-scroll-viewport') as HTMLDivElement;expect(viewport).not.toBeNull();Object.defineProperties(viewport,{scrollHeight:{configurable:true,value:1000},clientHeight:{configurable:true,value:300},scrollTop:{configurable:true,writable:true,value:400}});await act(async()=>viewport.dispatchEvent(new Event('scroll',{bubbles:true})));expect(card.textContent).toContain('Return to live');await act(async()=>{(card.querySelector('.process-return-live') as HTMLButtonElement).click()});expect(viewport.scrollTop).toBe(1000);expect(card.textContent).not.toContain('Return to live');await act(async()=>{(card.querySelector('.process-header') as HTMLButtonElement).click()});expect(card.querySelector('.process-scroll-viewport')).toBeNull()});
  it('keeps action semantics in normal tool labels',()=>{expect(semanticToolLabel({id:'r',kind:'read',lifecycle:'completed',title:'Read D:\\repo\\src\\router.js',occurredAt:'x',authority:'activity'})).toBe('Read router.js');expect(semanticToolLabel({id:'s',kind:'search',lifecycle:'completed',title:'Search selectRoute',occurredAt:'x',authority:'activity'})).toBe('Search selectRoute');expect(semanticToolLabel({id:'e',kind:'edit',lifecycle:'completed',title:'Edit D:\\repo\\router.js',occurredAt:'x',authority:'activity'})).toBe('Edit router.js');expect(semanticToolLabel({id:'t',kind:'todo',lifecycle:'completed',title:'Todowrite',occurredAt:'x',authority:'activity'})).toBe('Update tasks')});
  it('shows ordinary live appends immediately and paces only a large backlog',async()=>{vi.useFakeTimers();const value=timeline('p1',1,'live');value.spans[0]!.stream=[{id:'reason',kind:'narration',lifecycle:'updated',title:'Checking routes.',occurredAt:'x',authority:'activity'}];await act(async()=>root.render(<SessionTimeline timeline={value} onLoadEarlier={async()=>{}}/>));value.revision='p2';value.spans[0]!.stream[0]={...value.spans[0]!.stream[0]!,title:'Checking routes. Small append.'};await act(async()=>root.render(<SessionTimeline timeline={{...value,spans:[{...value.spans[0]!,stream:[value.spans[0]!.stream[0]!]}]}} onLoadEarlier={async()=>{}}/>));expect(host.querySelector('[data-testid="narration:reason"]')?.textContent).toBe('Checking routes. Small append.');const large='Checking routes. Small append.'+'.'.repeat(700);value.revision='p3';await act(async()=>root.render(<SessionTimeline timeline={{...value,spans:[{...value.spans[0]!,stream:[{...value.spans[0]!.stream[0]!,title:large}]}]}} onLoadEarlier={async()=>{}}/>));expect(host.querySelector('[data-testid="narration:reason"]')?.textContent).toBe('Checking routes. Small append.');await act(async()=>vi.advanceTimersByTimeAsync(24));const paced=host.querySelector('[data-testid="narration:reason"]')?.textContent??'';expect(paced.length).toBeGreaterThan('Checking routes. Small append.'.length);expect(paced.length).toBeLessThan(large.length);vi.useRealTimers()});
  it('prioritizes consequential failure over preceding narration',()=>{const failed=process();failed.state='failed';failed.stream=[{id:'n',kind:'narration',lifecycle:'completed',title:'Still investigating',occurredAt:'x',authority:'activity'},{id:'f',kind:'command',lifecycle:'failed',title:'node --test failed',occurredAt:'x',authority:'activity'}];expect(processSummary(failed)).toBe('node --test failed')});
});
