import { isRecord } from '../model/normalize';
export type StreamKind = 'narration'|'read'|'search'|'edit'|'command'|'agent'|'question'|'todo'|'web'|'other';
export interface StreamItem { id:string; kind:StreamKind; lifecycle:'started'|'updated'|'completed'|'failed'; title:string; detail?:string; occurredAt:string; authority:'activity'|'evidence' }
export interface ProcessSpan { id:string; parentId?:string; actor:'manager'|'worker'|'validator'; label:string; state:'live'|'waiting'|'completed'|'failed'|'cancelled'; startedAt:string; finishedAt?:string; stream:StreamItem[] }
export interface SessionSummary { id:string; rootJobId?:string; intent:string; state:'live'|'waiting'|'settled'; originHermesSessionId?:string; startedAt:string; settledAt?:string; updatedAt:string }
export interface SessionTimeline { session:SessionSummary; spans:ProcessSpan[]; revision:string }
const str=(r:Record<string,unknown>,k:string):string|undefined=>typeof r[k]==='string'?r[k] as string:undefined;
export function sessionsFromOverview(value:unknown):SessionSummary[]{ if(!isRecord(value)||!Array.isArray(value.sessions))return[]; return value.sessions.flatMap(raw=>{if(!isRecord(raw))return[];const id=str(raw,'id'),intent=str(raw,'intent'),state=str(raw,'state'),startedAt=str(raw,'started_at');if(!id||!intent||!startedAt||!['live','waiting','settled'].includes(state??''))return[];return[{id,intent,state:state as SessionSummary['state'],startedAt,updatedAt:str(raw,'updated_at')??startedAt,rootJobId:str(raw,'root_job_id'),originHermesSessionId:str(raw,'origin_hermes_session_id'),settledAt:str(raw,'settled_at')}];}); }
export function timelineFromJob(value:unknown):SessionTimeline|undefined{if(!isRecord(value)||!isRecord(value.session_timeline))return;const raw=value.session_timeline;if(!isRecord(raw.session)||!Array.isArray(raw.spans)||typeof raw.revision!=='string')return;const session=sessionsFromOverview({sessions:[raw.session]})[0];if(!session)return;const spans=raw.spans.flatMap((entry):ProcessSpan[]=>{if(!isRecord(entry)||typeof entry.id!=='string'||typeof entry.actor!=='string'||typeof entry.label!=='string'||typeof entry.state!=='string'||typeof entry.started_at!=='string')return[];const stream=Array.isArray(entry.stream)?entry.stream.flatMap((item):StreamItem[]=>{if(!isRecord(item)||typeof item.id!=='string'||typeof item.kind!=='string'||typeof item.lifecycle!=='string'||typeof item.title!=='string')return[];return[{id:item.id,kind:item.kind as StreamKind,lifecycle:item.lifecycle as StreamItem['lifecycle'],title:item.title,detail:str(item,'detail'),occurredAt:str(item,'occurred_at')??entry.started_at as string,authority:item.authority==='evidence'?'evidence':'activity'}];}):[];return[{id:entry.id,parentId:str(entry,'parent_id'),actor:entry.actor as ProcessSpan['actor'],label:entry.label,state:entry.state as ProcessSpan['state'],startedAt:entry.started_at,finishedAt:str(entry,'finished_at'),stream}];});return{session,spans,revision:raw.revision};}
export interface PositionedSpan extends ProcessSpan{lane:number;laneCount:number;top:number;height:number}
export function allocateLanes(spans:ProcessSpan[],pixelsPerMinute:number,now=Date.now()):PositionedSpan[]{if(!spans.length)return[];const start=Math.min(...spans.map(s=>Date.parse(s.startedAt)));const lanes:number[]=[];const result=[...spans].sort((a,b)=>Date.parse(a.startedAt)-Date.parse(b.startedAt)||a.id.localeCompare(b.id)).map(span=>{const from=Date.parse(span.startedAt),to=span.finishedAt?Date.parse(span.finishedAt):now;let lane=lanes.findIndex(end=>end<=from);if(lane<0){lane=lanes.length;lanes.push(to)}else lanes[lane]=to;return{...span,lane,laneCount:0,top:Math.max(0,((from-start)/60000)*pixelsPerMinute),height:Math.max(88,((Math.max(to,from)-from)/60000)*pixelsPerMinute)}});return result.map(s=>({...s,laneCount:Math.max(1,lanes.length)}));}
export const compactable=(span:ProcessSpan):boolean=>span.state==='completed'&&span.stream.length>0&&span.stream.every(i=>i.authority!=='evidence'&&i.lifecycle!=='failed'&&i.kind!=='question');
