import { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';
import { buildGeometry, bundleMundaneProcesses, type ConcurrencyCluster, type ProcessBundle, type ProcessSpan, type SessionTimeline as Timeline, type StreamItem, type TimelineProcess } from './model';

export interface TimelineBootstrapDiagnostic { suppliedClusters:number; viewportWidth:number; viewportHeight:number; listLoaded:boolean; renderedItems:number }
const GLYPH:Record<StreamItem['kind'],string>={narration:'',read:'◇',search:'⌕',edit:'◆',command:'›',agent:'↗',question:'?',todo:'○',web:'◎',other:'·'};
const basename=(value:string)=>{const clean=value.replace(/<[^>]+>/g,' ').replace(/["'`]/g,'').trim(),path=clean.match(/[A-Za-z]:[\\/][^\s]+|(?:\.\.?[\\/])?[^\s]+[\\/][^\s]+/)?.[0];return path?path.split(/[\\/]/).filter(Boolean).at(-1)??clean:clean};
const withoutVerb=(value:string)=>value.replace(/^(Read|Search|Edit|Write|Bash|Command|Run|Todo(?:write)?)\s*[:·-]?\s*/i,'').trim();
export function semanticToolLabel(item:StreamItem):string {const target=withoutVerb(item.title);switch(item.kind){case'read':return`Read ${basename(target)}`;case'search':return`Search ${target.replace(/^(?:Glob|Grep|Search)\s*/i,'')}`;case'edit':return`Edit ${basename(target)}`;case'todo':return'Update tasks';case'web':return`Fetch ${target}`;case'agent':return`Delegate ${target}`;case'command':return target.replace(/^Running\s+/i,'');default:return item.title}}
const elapsed=(span:ProcessSpan,now=Date.now())=>{const ms=Math.max(0,(span.finishedAt?Date.parse(span.finishedAt):now)-Date.parse(span.startedAt));return ms<60_000?`${Math.max(1,Math.round(ms/1000))}s`:`${Math.floor(ms/60_000)}m ${String(Math.round(ms/1000)%60).padStart(2,'0')}s`};
const lastWhere=(items:StreamItem[],predicate:(item:StreamItem)=>boolean)=>[...items].reverse().find(predicate);
export const processSummary=(process:TimelineProcess)=>{if('bundle'in process)return`${process.processes.length} short processes`;const consequential=lastWhere(process.stream,(item)=>item.lifecycle==='failed')??lastWhere(process.stream,(item)=>item.kind==='question')??lastWhere(process.stream,(item)=>item.authority==='evidence');if(consequential)return consequential.kind==='narration'?consequential.title:semanticToolLabel(consequential);const decision=process.actor==='manager'?lastWhere(process.stream,(item)=>item.kind==='narration'):undefined;return decision?.title??lastWhere(process.stream,(item)=>item.kind==='narration')?.title??(process.stream.at(-1)?.kind==='narration'?process.stream.at(-1)?.title:process.stream.at(-1)?semanticToolLabel(process.stream.at(-1)!):undefined)??'Recorded work'};

export const TEXT_RENDER_IMMEDIATE=512,TEXT_RENDER_PACE_MS=24;
const pacedStep=(size:number)=>size<=12?2:size<=48?4:size<=96?8:Math.min(256,Math.ceil(size/4));
export function nextPacedText(text:string,start:number):string{const end=Math.min(text.length,start+pacedStep(text.length-start)),max=Math.min(text.length,end+8);for(let index=end;index<max;index++)if(/[\s.,!?;:)\]]/.test(text[index]??''))return text.slice(0,index+1);return text.slice(0,end)}
function usePacedText(value:string,active:boolean){const [shown,setShown]=useState(value),shownRef=useRef(value),target=useRef(value),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);shownRef.current=shown;useEffect(()=>{target.current=value;const sync=(text:string)=>{shownRef.current=text;setShown(text)};if(!active||!value.startsWith(shownRef.current)||value.length<=shownRef.current.length||value.length-shownRef.current.length<=TEXT_RENDER_IMMEDIATE){if(timer.current)clearTimeout(timer.current);timer.current=undefined;sync(value);return}const run=()=>{timer.current=undefined;const text=target.current,current=shownRef.current;if(!active||!text.startsWith(current)||text.length<=current.length||text.length-current.length<=TEXT_RENDER_IMMEDIATE){sync(text);return}sync(nextPacedText(text,current.length));if(shownRef.current.length<text.length)timer.current=setTimeout(run,TEXT_RENDER_PACE_MS)};if(!timer.current)timer.current=setTimeout(run,TEXT_RENDER_PACE_MS);return()=>{if(timer.current)clearTimeout(timer.current);timer.current=undefined}},[value,active]);return shown}
function Narration({item,live}:{item:StreamItem;live:boolean}){const text=usePacedText(item.title,live&&item.lifecycle!=='completed');return item.title.length>420?<details className="narration-disclosure"><summary className="agent-prose"><span data-testid={`narration:${item.id}`}>{text.slice(0,280)}{text.length>280?'…':''}</span> <span>Read full explanation</span></summary><p className="agent-prose" data-testid={`narration-full:${item.id}`}>{item.title}</p></details>:<p className="agent-prose" data-testid={`narration:${item.id}`}>{text}</p>}
function ToolRow({item}:{item:StreamItem}){const running=item.lifecycle==='started'||item.lifecycle==='updated',failed=item.lifecycle==='failed';return <details className={`tool-row tool-${item.kind} lifecycle-${item.lifecycle}`}><summary><span className="tool-glyph">{failed?'!':item.kind==='command'&&item.lifecycle==='completed'?'✓':GLYPH[item.kind]}</span><span className={running?'tool-title running':'tool-title'}>{running&&item.kind==='command'?'Running ':''}{semanticToolLabel(item)}</span>{failed&&<span className="tool-result">failed</span>}</summary>{item.detail&&<pre>{item.detail}</pre>}</details>}
function Stream({span,loading,loadEarlier}:{span:ProcessSpan;loading?:boolean;loadEarlier?:()=>void}){return <div className="process-stream" tabIndex={0} data-testid={`stream:${span.id}`}>{span.streamBounds.hasEarlier&&<button className="load-earlier" disabled={loading} onClick={loadEarlier}>{loading?'Loading…':'Load earlier activity'}</button>}{!span.streamBounds.complete&&!span.streamBounds.hasEarlier&&<div className="stream-bound">Recorded stream begins here</div>}{span.stream.length?<div className="stream-viewport" data-testid={`stream-viewport:${span.id}`}>{span.stream.map((item)=><div className={`stream-item stream-${item.kind}`} key={item.id}>{item.kind==='narration'?<Narration item={item} live={span.state==='live'}/>:<ToolRow item={item}/>}</div>)}</div>:<div className="truthful-working">{span.state==='live'?<><span className="working-mark"/>Working…</>:'No public stream was recorded.'}</div>}</div>}
const processSpans=(process:TimelineProcess):ProcessSpan[]=>'bundle'in process?(process as ProcessBundle).processes:[process];

function ClusterRow({cluster,expanded,toggle,loading,loadEarlier}:{cluster:ConcurrencyCluster;expanded:Set<string>;toggle:(id:string)=>void;loading:Set<string>;loadEarlier:(span:ProcessSpan)=>void}){const disclosures=cluster.processes.filter(({process})=>expanded.has(process.id));return <div className={`cluster-row lanes-${cluster.laneCount}`} data-testid={cluster.id}><div className="chronology-gap" style={{height:cluster.gapBefore}} aria-hidden="true"/><div className="cluster-canvas" style={{height:cluster.height}}><time>{new Date(cluster.start).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time><div className="time-node" aria-hidden="true"/>{cluster.processes.map(({process,lane,top,height})=>{const settled=!['live','waiting'].includes(process.state);return <article key={process.id} className={`span-card actor-${process.actor} state-${process.state}${'bundle'in process?' process-bundle':''}`} style={{top,height,left:`calc(${lane/cluster.laneCount*100}% + 70px)`,width:`calc(${100/cluster.laneCount}% - ${70/cluster.laneCount}px - 14px)`}}><button className="span-head" onClick={settled?()=>toggle(process.id):undefined} aria-expanded={expanded.has(process.id)}><span className="role-chip">{process.actor}</span><span className="process-title">{process.label.replace(/^(Manager|Worker|Validation)\s*[·:]?\s*/i,'')||process.label}</span><span className="span-meta">{process.state==='live'?'LIVE':elapsed(process)}{settled?'  ›':''}</span></button>{process.state==='live'?<Stream span={process} loading={loading.has(process.id)} loadEarlier={()=>loadEarlier(process)}/>:<div className="compact-summary"><span>{processSummary(process)}</span><small>{'bundle'in process?`${process.processes.length} processes`:`${process.stream.length} event${process.stream.length===1?'':'s'}`}</small></div>}</article>})}</div>{disclosures.map(({process})=><div className={`inline-disclosure actor-${process.actor}`} key={`disclosure:${process.id}`} data-testid={`disclosure:${process.id}`}><div className="disclosure-rail" aria-hidden="true"/><header><span className="role-chip">{process.actor}</span><b>{process.label}</b><span>{elapsed(process)}</span><button onClick={()=>toggle(process.id)}>Close</button></header>{processSpans(process).map((span)=><Stream key={span.id} span={span} loading={loading.has(span.id)} loadEarlier={()=>loadEarlier(span)}/>)}</div>)}</div>}

export function SessionTimeline({timeline,onLoadEarlier,onBootstrapDiagnostic}:{timeline:Timeline;onLoadEarlier:(span:ProcessSpan)=>Promise<void>;onBootstrapDiagnostic?:(diagnostic:TimelineBootstrapDiagnostic)=>void}){const [zoom,setZoom]=useState(8),[expanded,setExpanded]=useState<Set<string>>(()=>new Set()),[following,setFollowing]=useState(true),[newCount,setNewCount]=useState(0),[clock,setClock]=useState(Date.now()),[loading,setLoading]=useState<Set<string>>(()=>new Set());const listRef=useRef<HTMLDivElement|null>(null),listHostRef=useRef<HTMLDivElement|null>(null),revision=useRef(timeline.revision),rearmRequested=useRef(false),listLoaded=useRef(false),renderedItems=useRef(new Set<string>());
  useEffect(()=>{if(timeline.session.state==='settled')return;const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer)},[timeline.session.state]);useEffect(()=>{if(revision.current!==timeline.revision&&!following)setNewCount((count)=>count+1);revision.current=timeline.revision},[timeline.revision,following]);const processes=useMemo(()=>bundleMundaneProcesses(timeline.spans,clock),[timeline.spans,clock]),clusters=useMemo(()=>buildGeometry(processes,zoom,clock),[processes,zoom,clock]);const reportBootstrap=()=>{if(!onBootstrapDiagnostic)return;const bounds=listHostRef.current?.getBoundingClientRect();onBootstrapDiagnostic({suppliedClusters:clusters.length,viewportWidth:bounds?.width??0,viewportHeight:bounds?.height??0,listLoaded:listLoaded.current,renderedItems:renderedItems.current.size})};useLayoutEffect(()=>{const list=listRef.current;if(!list)return;listLoaded.current=true;if(following)list.scrollTop=list.scrollHeight;reportBootstrap()},[clusters,following]);useEffect(()=>{reportBootstrap();const host=listHostRef.current;if(!host||!onBootstrapDiagnostic||typeof ResizeObserver==='undefined')return;const observer=new ResizeObserver(reportBootstrap);observer.observe(host);return()=>observer.disconnect()},[clusters.length,onBootstrapDiagnostic]);
  const onScroll=(event:React.UIEvent<HTMLDivElement>)=>{const viewport=event.currentTarget,distance=viewport.scrollHeight-viewport.scrollTop-viewport.clientHeight,atEnd=distance<=40;if(atEnd){if(rearmRequested.current||following){setFollowing(true);setNewCount(0)}rearmRequested.current=false}else if(distance>40){setFollowing(false);rearmRequested.current=false}};const jumpLatest=()=>{const viewport=listRef.current;if(!viewport)return;viewport.scrollTop=viewport.scrollHeight;const distance=viewport.scrollHeight-viewport.scrollTop-viewport.clientHeight;if(distance<=40){setFollowing(true);setNewCount(0);rearmRequested.current=false}else rearmRequested.current=true};const loadEarlier=async(span:ProcessSpan)=>{if(!span.streamBounds.cursor||loading.has(span.id))return;setLoading((current)=>new Set(current).add(span.id));try{await onLoadEarlier(span)}finally{setLoading((current)=>{const next=new Set(current);next.delete(span.id);return next})}};const started=new Date(timeline.session.startedAt),ended=timeline.session.settledAt?Date.parse(timeline.session.settledAt):clock,total=Math.max(0,ended-started.getTime());
  return <section className="timeline-panel"><header className="timeline-header"><div className="session-mast"><div><h1>{timeline.session.intent}</h1><p>Hermes · {started.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</p><details className="request-disclosure"><summary>Show full request</summary><p>{timeline.session.intent}</p></details></div><span className={`session-state state-${timeline.session.state}`}>{timeline.session.state} · {Math.floor(total/60_000)}m {String(Math.round(total/1000)%60).padStart(2,'0')}s</span></div><label className="zoom">Timeline density <input type="range" min="3" max="18" value={zoom} onChange={(event)=>setZoom(Number(event.target.value))}/><b>{zoom}</b></label></header><div className="timeline-list-host" ref={listHostRef}><div ref={listRef} className="timeline-list" onScroll={onScroll}><div className="board-label">TIME <span>↓</span></div>{clusters.map((cluster)=>{renderedItems.current.add(cluster.id);return <ClusterRow key={cluster.id} cluster={cluster} expanded={expanded} loading={loading} toggle={(id)=>setExpanded((current)=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next})} loadEarlier={(span)=>void loadEarlier(span)}/>})}<div className="latest-rule"><span>{timeline.session.state==='settled'?'FINISHED':'LIVE'}</span></div></div></div>{!following&&<button className="return-live" onClick={jumpLatest}>↓ {timeline.session.state==='settled'?'Jump to latest':'Return to live'}{newCount?` · ${newCount} updates`:''}</button>}</section>}
